Prefix: "&b[ FarmHunter ]"
LobbyCooldown: 60
SeekerWait: 30
gameOverRewards:
  - "give {player} stone 1"
MainLobby: null

Language:
  noPermission: "&b没有权限!"
  pluginReloaded: "&b成功加载插件!"
  arenaCreated: "&a游戏场地成功创建"
  arenaMaxPlayers: "&a游戏场地最大玩家数量已设置为 &b<0> &a个玩家"
  arenaMinPlayers: "&a游戏场地最小玩家数量已设置为 &b<0> &a个玩家"
  arenaTime: "&a游戏场地时间已设置为 &b<0> &a秒"
  arenaSpawn: "&a已设置 &b<0> &a的出生点"
  arenaLobby: "&a已设置该竞技场的大厅"
  arenaNotExist: "&c没有相应的游戏场地"
  arenaLimited: "&c该竞技场已经满人，无法进入"
  arenaNotEnough: "&c玩家数量不足! 中止倒计时"
  arenaStarted: "&c该竞技场正在游戏中! 无法进入"
  inGame: "&c你已经在游戏里了! 无法再次进入"
  leave: "&a你已离开了 <0> 场地"
  join: "&a你已加入了 <0> 场地"
  playersLeave: "&a一名玩家离开了游戏，目前人数 &7<0>/<1>"
  playersJoin: "&b一名玩家加入了游戏，目前人数 &7[<0>/<1>]"
  itemCooldown: "&b你需要等待 <0> 秒后才能使用道具"
  lobbyCooldown: "&b距离游戏开始还有 <0> 秒"
  gameStart: "&c游戏正式开始!"
  seekerStarted: "&c距离寻找者开始寻找还有 <0> 秒"
  gameCooldown: "&c距离游戏结束还有 <0> 秒"
  gameOver: "&c游戏结束"
  gameOverInfo:
    - "&b&l&m--------------------------------------"
    - "&b"
    - "           &b&l获胜方: <0>"
    - "           &e恭喜所有获胜方获得最终胜利"
    - "     &7奖励"
    - "     &55 游戏经验"
    - "&b"
    - "&b&l&m--------------------------------------"

