name: FarmHunter
version: 1.0.1-SNAPSHOT
main: com.github.hotpee.farmhunter.FarmHunter
api-version: 1.13
softdepend: [LibsDisguises]
commands:
  farmhunter:
    aliases: [fh]
    description: Command help for FarmHunter

